{% set name = "softworks" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/softworks-{{ version }}.tar.gz
  sha256: fceb70ca81e23ddef24e8b621c5b1795ce945087aa52b3542e35ec075cae0fe0

build:
  noarch: python
  number: 0

requirements:
  host:
    - pip >=22.2.2
    - flit >=3.7.1
    - python >=3.7
  run:
    - python >=3.7
    - virtue >=0.3.2

test:
  imports:
    - softworks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.cascode-labs.org/softworks/
  summary: Software and documentation view types in Cadence Virtuoso
  dev_url: https://github.com/cascode-labs/softworks
  doc_url: https://www.cascode-labs.org/softworks/
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - curtisma
